name: psqlgml-ci

on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install
        run: |
          sudo apt install -y graphviz
          pip install tox
      - name: static checks
        run: tox -e static
        if: matrix.python == 3.6
      - name: tests
        run: tox -e py
